import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/provider/modal-provider";
import { Toaster } from "react-hot-toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hello Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 4000,
              style: {
                background: "#f0fdf4", // bg-green-50
                border: "1px solid #4ade80", // border-green-400
                color: "#065f46", // text-green-800
                boxShadow: "0px 4px 8px rgba(0,0,0,0.1)",
                fontSize: "14px",
                fontWeight: 500,
              },
            }}
          />
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
